### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by imanassypov** [carlashley/tccprofile#10]
./tccprofile.py --allfiles /opt/cisco/amp/ampdaemon --payload-description="This profile whitelists Cisco AMP daemon" --payload-identifier="com.company.cisco.tcc.privacy.whitelist" --payload-name="Privacy Settings Whitelist - Cisco AMP" --payload-org="My Org" --payload-version="1" -o cisco.amp.fulldisk.mobileconfig
Traceback (most recent call last):
  File "./tccprofile.py", line 1221, in <module>
    main()
  File "./tccprofile.py", line 1215, in main
    tcc_profile.build_profile(allow=args.allow_app)
  File "./tccprofile.py", line 694, in build_profile
    path=app)
  File "./tccprofile.py", line 805, in _get_code_sign_requirements
    mimetype = self._get_file_mime_type(path=path)
  File "./tccprofile.py", line 774, in _get_file_mime_type
    result = result.replace(' ', '').replace('\n', '').split(':')[1].split('/')[1]
IndexError: list index out of range

**Comment by imanassypov** [comment]
- requires sudo to run

**Comment by carlashley** [comment]
What are the permissions on the binary and the directory path?

If the permissions for any of the folders or files in the path require higher access, then yes, it will fail if not run as `sudo`. I’ll have a look at how this can be better handled from a error/exception point of view.

**Comment by carlashley** [comment]
I realised you closed the issue, but I've implemented some fixes to better handle situations such as the one you raised here :)

https://github.com/carlashley/tccprofile/commit/fc5265b68e1a764cdf0a5c528c3fa3efbb54a652
