### ISSUE TITLE
GoToAssist Customer (1610) Not Working

### ISSUE THREAD

**Issue by clifford64** [carlashley/tccprofile#11]
I tried using the GUI with the GoToAssist Customer (1610). It creates the profile and I can deploy it via airwatch. It deploys successfully, but it does not actually make any changes. I have tried it with PostEvent and Accessibility.

**Comment by carlashley** [comment]
This really isn’t a big in`tccprofile.py`. I suggest checking out #tcc in the Macadmins Slack to see if anyone else has success with creating a profile for that app.
