### ISSUE TITLE
UnicodeDecodeError:  for --appleevents 

### ISSUE THREAD

**Issue by skull4d** [carlashley/tccprofile#3]
I am trying to create a profile with this tool and getting below error. 

> /tccprofile.py --appleevents /Applications/Utilities/Terminal.app,/Applications/Microsoft\ Outlook.app --payload-description=“Test TCC Whitelist for Microsoft Outlook" --payload-name="TCC Whitelist terminal-Outlook" --payload-org=“My Great Company”\n --payload-version=1 --payload-identifier="com.carlashley.github" -o Terminal-Microsoft_TCC.mobileconfig --allow --sign=“xxxx”
> Traceback (most recent call last):
>   File "./tccprofile.py", line 559, in <module>
>     main()
>   File "./tccprofile.py", line 548, in main
>     plistlib.writePlist(tccprofiles.template, filename)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 94, in writePlist
>     writer.writeValue(rootObject)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 252, in writeValue
>     self.writeDict(value)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 281, in writeDict
>     self.writeValue(value)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 258, in writeValue
>     self.writeArray(value)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 287, in writeArray
>     self.writeValue(value)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 252, in writeValue
>     self.writeDict(value)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 281, in writeDict
>     self.writeValue(value)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 239, in writeValue
>     self.simpleElement("string", value)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 172, in simpleElement
>     value = _escapeAndEncode(value)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 222, in _escapeAndEncode
>     return text.encode("utf-8")             # encode as UTF-8
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

**Comment by carlashley** [comment]
I'll have a look at Microsoft Outlook in particular (I've tried replicating with Microsoft Excel, did not get the same result).

Looking at the command you've pasted, there is a `\n` character in the command - just try that again without the `\n` and see what happens.
The flag the `\n` is in is: `--payload-org=“My Great Company”\n`

**Comment by skull4d** [comment]
.
Hi Carls,
Thank for replying.

I have removed \n and it worked without error.

But \n flag is also mentioned in README Usage:
Check the attached screenshot.

**Comment by carlashley** [comment]
Woops! That snuck through in a copy+pasta operation. Fixed with https://github.com/carlashley/tccprofile/commit/b7e9e837f3672eb941ba3c9c5303f398ea9a9d2e.
