### ISSUE TITLE
Feature suggestion:  watch attribution logs and auto generate a profile

### ISSUE THREAD

**Issue by sullrich** [carlashley/tccprofile#4]
Great work on this so far Carl!

A great addition to your script would be the ability to invoke tccprofile.py with the ability for it to watch the attribution logs and automatically generate a profile.  Example of my pipedream request:

./tccprofile.py --watch -o newprolfile.mobileconfig
Watching attribution logs.  Press ctrl-c when you are finished.
^C
Automatically generated profile: newprofile.mobileconfig

-- SNIP --

The idea being that tccprofile.py gathers the data from the command log stream --debug --predicate 'subsystem == "com.apple.TCC" AND eventMessage BEGINSWITH "AttributionChain"' and automatically creates a profile for whatever the system notes being blocked/rejected.

Thanks for consideration of this feature request!

**Comment by carlashley** [comment]
This is not something that I'm particular to implemented, however, if a PR comes along, I'm happy to review.
